device: cuda:0
model_name: llama3.1
subspace_data_path: data/combined_subspace/3Ks_subspace_data_llama3.1.pkl
input_file: data/instructions/test/xstest_safe.json
output_file: data/responses/llama3.1/xstest_llama3.1_results.json
batch_size: 32
max_new_tokens: 128
file_rename: False
prompt_column: prompt
strength: -0.1,-0.2,-0.3,-0.4,-0.45,-0.5